name: angulardart_flight_school
version: 0.0.1
author: Pierre Reliquet
description: A sample contact management app made for the AngularDart Flight School given by the GDG Nantes
environment:
  sdk: 1.6.0
dependencies:
  angular: 0.14.0
  browser: 0.10.0+2
  js: any
  shadow_dom: any
transformers:
- angular:
   # https://github.com/angular/angular.dart/issues/1279 for now we need to add manually the files to include in the transformer
   html_files:
    - web/partials/edit.html
    - web/partials/list.html
    - web/partials/view.html
